apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flask-api.serviceAccountName" . }}
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
